apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clustersito
  region: eu-west-1
vpc:
  id: "vpc-072621e13517a8f10"
  subnets:
    public:
      eu-west-1a:
        id: "subnet-02a30d24db5e7fb00"
      eu-west-1b:
        id: "subnet-0ccb430b1fb07f722"

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key