---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unnamed-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unnamed-exporter
subjects:
  - kind: ServiceAccount
    name: unnamed-exporter
    namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unnamed-exporter
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unnamed-exporter
  namespace: monitoring
