apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: iluminati@google.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "dcalvo.dev"
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: caught you looking!
          secretAccessKeySecretRef:
            name: staging-route53-credentials-secret
            key: secret-access-key