apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-copy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello-kubernetes-copy
  template:
    metadata:
      labels:
        name: hello-kubernetes-copy
    spec:
      containers:
        - name: app
          image: paulbouwer/hello-kubernetes:1.8
          ports:
            - containerPort: 8080
