apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  groups:
    - system:authenticated
  usages:
    - digital signature
    - key enciperhment
    - server auth
  request: | #cat jane.csr | base64
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5N
    QXNHQTFVRUF3d0VhbUZ1WlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0Nn
    Z0VCQU5pd1RjV0xGU3RJd3RCclN2TnBLb2NWTFZVZDF0Z2Y1bzlLUVZMN1ZrZ2lqYlBXCnFXRUFj
    ZUZBTks1eVlKRFFzek0zRzFtTXZacVBWM2g4MjdmbGFUZnJrL1M0MjBielZxdVNFR0JhalhtQUoy
    WWcKNysrdWd0WkhraTc0MkhHbXEyREg2dnppRVZBQ1RWdjJLSnlwaE5aQ3dtdWoyMHB0OExsMi9P
    aWVDK3lGNVZLVQpHdGNTWURxR0tTUTZMR3ArandFUk9TVzJLUFRGL1h6R1ZoMlFHaEthK01qY3NZ
    d3pVbGNEamUvQkx2M1cvODlQCmMrMVdjZG1hMzd4bkJ6VndrVFBNZHRqaFprWDUvSS81a1Q1dEI5
    ZXhLSEF0NlVPamkva0FKWXZqZGtUblFpVHkKcDJhVWtQSVQzdktDUVk1eElJK1RvbnVTbERiY3ZI
    TzNVVHhjejU4Q0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQS92MlQzUmZlRzdJ
    Ymp6UWNwSm5IM2Jud21sVlR4VkVrRWN5RUJkQnMyN1dLSldPbVZGQVg3CkJEMW1QSlZYYVgzeXI4
    Vy9QcnUyd3pvOUVBN0YwbDk2QnRpUFhVb2FOTklUbzNWOXVqTExqMlNuWlg4cEowM0YKTDVMcnl1
    U1JPUWYreWZ5UjRpZCtkSXJNdkk1ZnVoRUxvVGFjSDNsN29paTdVWXo5TnRpeStQYVphSGlpVlVF
    QgovKzR4cUl1ajA0SUVZZWhxQmxneUdaYlhUZ1Zvc2JBd29iZWZoblFNRVN0T2hRdUZxdDNrdFFt
    L2JZSks5RTBrCk9YVC9xNzJTS3BoZlBtNXJDRXU2b3lDQkk4MERjbkxaLzZTSnU3ZXZkK2Vmckxn
    TnU1QVVaQzdiUmU2R1FwMWoKWkNxWkxsblI1ZFVzRC8yYXhVVDJocEZXakl2czUvYUIKLS0tLS1F
    TkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
