apiVersion: v1
kind: Config

current-context: dev-user@google.com

clusters:
  - name: my-kube-playground
    cluster:
      certificate-authority: ca.crt
      server: https://my-kube-playground:6433
contexts:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin
users:
  - name: my-kube-admin
    user:
      client-certificate:
      client-key:

