apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-dcalvo-dev
  namespace: default
spec:
  secretName: dcalvo-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hello-kubernetes.dcalvo.dev