apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: iluminati@google.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "dcalvo.dev"
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: caught you looking!
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key