apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
  annotations:
    kubernetes.io/ingress.class: "nginx" # use the one that corresponds to your ingress controller.
spec:
  rules:
  - host: asd.dcalvo.dev
    http:
      paths:
      - backend:
          serviceName: foo
          servicePort: 80