apiVersion:
kind:
metadata:
  name:
spec:
  rules:
    - http:
        paths:
          - path: /wear
            backend:
              serviceName: wear-service
              servicePort: 80
          - path: /watch
              backend:
                serviceName: watch-service
                servicePort: 80