apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-v2
  {{- template "mychart.labels" . }}
data:
  {{- range $key, $val := .Values.favourite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ include "mychart.app" . | indent 2 }}
  {{-  $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}

