apiVersion: v1
kind: ConfigMap
metadata:
  name: confa
  {{- template "mychart.labels" . }}
data:
{{ (.Files.Glob "configs/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: el-secreto
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}