apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: alpine
      name: apine
      command: ["/bin/sh", "-c"]
      args: ["shuf -i 0-100 >> /opt/number.out"]
      volumeMounts:
        - mountPath: /opt
          name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /dataA
        type: Directory