apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    stoage: 1Gi
  hostPath: #This gets replaced with cloud options like awsElasticBlockStore
    path: /tmp/data #Not to be used in production!