apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
    - name: mypod
      image: mypod
      ports:
        - containerPort: 8080
      env:
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_password