apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
    - name: mypod
      image: mypod
      ports:
        - containerPort: 8080
      volumes:
        - name: app-secret-volume
          secret:
            secretName: app-secret