apiVersion: v1
kind: Pod
metadata:
  name: mypod-app
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ["sh", "-c", "The app is running! :D"]
  initContainer:
    - name: init-myservice
      image: busybox
      command: ["sh", "-c", "git clone somerepo"]