version: '3'

services:

  web:
    build:
      context: ./web
      dockerfile: ./web/Dockerfile
    ports:
    - "8080:80"

  db:
    image: mysql:5.7
    ports:
    - "33006:3306"
    build:
      context: ./db
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
      MYSQL_DATABASE: "wordpress"